import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import icons from './assets/icons.svg'
import Header from '@/components/Header'

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

const paperlogy = localFont({
  src: [
    { path: './fonts/Paperlogy-4Regular.ttf', weight: '400' },
    { path: './fonts/Paperlogy-6SemiBold.ttf', weight: '600' },
    { path: './fonts/Paperlogy-7Bold.ttf', weight: '700' },
  ],
  variable: '--font-paperlogy',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko'>
      <body className={`${pretendard.className} ${paperlogy.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
